### ISSUE TITLE
Add instructions in readme to change directories to SageMaker

### ISSUE THREAD

**Issue by noahsdonaldson** [aws-samples/amazon-bedrock-workshop#34]
In the ReadMe you have instructions to clone the repository and install dependencies, however, you need to first CD to the SageMaker directory in Jupyter for this to work correctly. 

Instructions here - https://github.com/aws-samples/amazon-bedrock-workshop/#clone-and-use-the-notebooks

**Comment by athewsey** [comment]
As a reminder to myself or info for whoever comes to tackle this first: Just note that this `cd` is usually required for SM Notebook Instances (where the default terminal directory is `/home/ec2-user` but the Jupyter root folder is `/home/ec2-user/SageMaker`) but **NOT** in SM Studio (where both the default terminal directory and the Jupyter root folder are `/home/sagemaker-user`).

As such it's not applicable to everybody (and I'd usually suggest Studio as the default for workshops or new SageMaker users due to the extra features), but I have seen new SM NBI users get confused about this in the past with other samples... So I do agree it's a fair ask to try and include this tip in the guidance as clearly as we can.

**Comment by w601sxs** [comment]
Closing this; please refer to the latest bedrock workshop update
